# Generated by Django 4.1.7 on 2023-04-11 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0004_bmirecord_created_date_alter_bmirecord_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmirecord',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
