# Generated by Django 4.1.7 on 2023-03-24 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellphone', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=255)),
                ('image_file', models.BinaryField()),
            ],
        ),
    ]
