# Generated by Django 2.2.28 on 2023-03-25 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cellphone', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
