# Generated by Django 2.2.28 on 2023-04-07 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cellphone', '0004_cellphone_currency_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Cellphone',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
    ]
